### ISSUE TITLE
Failed to start codile.service: Unit codile.service not found.

### ISSUE THREAD

**Issue by ChaDonSom** [dimkr/codile#2]
Not sure if this one is a duplicate of #1 or not.

When I attempt to start from Terminal by running `codile`, this is what it returns:

```bash
Failed to start codile.service: Unit codile.service not found.
```

I installed on a Lenovo C330 Chromebook (hana board, arm64 processor) running Chrome OS 86 on stable, using the `codile_0.0.1_arm64.deb` file of release '[0.0.1-ba746af](https://github.com/dimkr/codile/releases/tag/0.0.1-ba746af)'.

So far, I've only tried restarting the Linux container and restarting the Chromebook.

Excited to try it out, though!

**Comment by dimkr** [comment]
Thanks @ChanDonSom, fixed.
