### ISSUE TITLE
git repository is not recognized

### ISSUE THREAD

**Issue by cjvanzwol** [dimkr/codile#4]
In the source control widow it says: No repository found.

I cloned the repo again, to be sure there was git source in the folder.
Then I go to File > Open workspace > choose folder to open.
The repo is still not shown.

I removed the package (apt purge) and downloaded the .deb again and installed the package again. Still the same.

**Comment by dimkr** [comment]
Thanks for reporting, @cjvanzwol. Do you have `git` installed?

**Comment by cjvanzwol** [comment]
Yes, I have git installed
```
$ git --version
git version 2.20.1
```


Next I have tried to creat a new directory and do `git init`, bur still no repo is found by the application.


Also, I googled the problem before reporting this issue. But first i did not find a solution.
A second search i searched specific for theia related git problems and found this: https://github.com/eclipse-theia/theia/issues/7860.
Don know if this helps.

**Comment by cjvanzwol** [comment]
I solved it.
The built-in git extention for VSCode is not installed by default for Codile.

After installing the extension: [Git (built-in)](https://open-vsx.org/extension/vscode/git), the repo was recognised by Codile.
(Although the commit button is missing. But maybe this is a extension issue. I'll look into this later. For now my problem is solved.)

Maybe you could consider keeping git buyilt-in?

**Comment by dimkr** [comment]
Sounds like a useful extension and something almost every IDE user would benefit from, indeed. I'll add it.

**Comment by dimkr** [comment]
Please try 0.0.1-v9. If you're happy with it, I'll close this issue.

**Comment by cjvanzwol** [comment]
> Please try 0.0.1-v9. If you're happy with it, I'll close this issue.

YES! It works! In version 0.0.1-v9 all buttons show like i expect them to.
